# Generated by Django 3.2.5 on 2022-02-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Auto',
        ),
    ]
